### PR TITLE
fix(armies): Fix armies/lookup return value

### LINKED ISSUE #60: [BUG] Return error in /armies/lookup
## Detailed bug description
the root `/armies/lookup` returns all armies data instead of just name and id

## Expected comportment
return only names and ids

### PR DESCRIPTION
**Pull request by Victoire-Rabeau**
## Problem

The route `/armies/lookup` was returning all armies data instead of credentials only

## Changes

Added an iteration on the data to extract credentials.
Also made the load method public to increase the route's rapidity
---
Closes #60

### CODE REVIEW

File: src/army/ArmyCredentials.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+export class ArmyCredentials {
+    constructor(id: string, name: string) {
+        this.id = id;
+        this.name = name;
+    }
+
+    public id: string;
+    public name: string;
+}
```
Comment (Victoire-Rabeau) [inline src/army/ArmyCredentials.ts:9]: add empty line

File: src/army/army.controller.ts [hunk 2]
```diff
@@ -3,6 +3,7 @@ import { Controller, HttpCode, HttpStatus, Get, Param, NotFoundException } from
 import { ArmyService } from "./army.service";
 import { ArmyDTO } from "./army.dto";
 import { Army } from "./army.entity";
+import {ArmyCredentials} from "./ArmyCredentials";
```
Comment (Victoire-Rabeau) [inline src/army/army.controller.ts:6]: spaces

File: src/army/army.entity.ts [hunk 3]
```diff
@@ -55,8 +55,8 @@ export class Army {
     public specialItemCategories: SpecialItemCategory[] = [];
     public specialItems: SpecialItem[] = []
 
-    @AfterLoad()
-    private async loadEntities() {
+    // @AfterLoad()
```
Comment (Victoire-Rabeau) [inline src/army/army.entity.ts:58]: remove line

File: src/army/army.service.ts [hunk 4]
```diff
@@ -3,6 +3,7 @@ import { Repository } from "typeorm";
 import { InjectRepository } from "@nestjs/typeorm";
 
 import { Army } from "./army.entity";
+import {ArmyCredentials} from "./ArmyCredentials";
```
Comment (Victoire-Rabeau) [inline src/army/army.service.ts:6]: remove import

**Review by Victoire-Rabeau — COMMENTED** [review]
small fixes but ok

**Review by Victoire-Rabeau — COMMENTED** [review]
ok
